openapi: 3.0.2
info:
  title: API Title
  version: '1.0'
  contact:
    name: My service
  description: My service
servers:
  - url: /
paths:
  /health:
    get:
      summary: Health
      tags:
        - System
      responses:
        '200':
          description: OK
      operationId: getHealth
      description: Health check
  '/health/validator/{int}':
    parameters:
      - schema:
          type: integer
        name: int
        in: path
        required: true
    get:
      summary: Validator test
      tags:
        - System
      responses:
        '200':
          description: OK
      operationId: getHealthValidatorInt
      description: For openapi validator test
tags:
  - name: System
